# Generated by Django 5.2.16 on 2026-07-23 08:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='varieties/')),
                ('kgs_per_bag', models.DecimalField(decimal_places=2, help_text='Mandatory standard Kgs per bag', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Varieties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('shortcut_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits starting with 6, 7, 8, or 9.', regex='^[6-9]\\d{9}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties', to='inventory.place')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('STAFF', 'Staff')], default='STAFF', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Outward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField(editable=False, unique=True)),
                ('invoice_no', models.CharField(editable=False, max_length=50, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bags', models.PositiveIntegerField()),
                ('total_kgs', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('lf_toggle', models.BooleanField(default=False, verbose_name='LF Toggle (Yes/No)')),
                ('total_value', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outward_entries', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outwards', to='inventory.party')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outwards', to='inventory.variety')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['variety', '-date', '-id'], name='inventory_o_variety_3a2f4f_idx'), models.Index(fields=['party', '-date'], name='inventory_o_party_i_1f8f73_idx'), models.Index(fields=['-date'], name='inventory_o_date_d414d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Inward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField(editable=False, unique=True)),
                ('invoice_no', models.CharField(editable=False, max_length=50, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bags', models.PositiveIntegerField()),
                ('total_kgs', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('lf_toggle', models.BooleanField(default=False, verbose_name='LF Toggle (Yes/No)')),
                ('total_value', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inward_entries', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inwards', to='inventory.party')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inwards', to='inventory.variety')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['variety', '-date', '-id'], name='inventory_i_variety_f81fc6_idx'), models.Index(fields=['party', '-date'], name='inventory_i_party_i_acfa50_idx'), models.Index(fields=['-date'], name='inventory_i_date_23c69b_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyStockSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opening_bags', models.IntegerField(default=0)),
                ('inward_bags', models.IntegerField(default=0)),
                ('outward_bags', models.IntegerField(default=0)),
                ('closing_bags', models.IntegerField(default=0)),
                ('opening_kgs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('inward_kgs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('outward_kgs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('closing_kgs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='inventory.variety')),
            ],
            options={
                'ordering': ['-date', 'variety__name'],
                'indexes': [models.Index(fields=['variety', '-date'], name='inventory_d_variety_b2ad19_idx'), models.Index(fields=['-date'], name='inventory_d_date_007d08_idx')],
                'unique_together': {('variety', 'date')},
            },
        ),
    ]
