# Generated by Django 5.2.16 on 2026-07-23 09:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dailystocksummary',
            name='inventory_d_variety_b2ad19_idx',
        ),
        migrations.RemoveIndex(
            model_name='dailystocksummary',
            name='inventory_d_date_007d08_idx',
        ),
        migrations.RemoveIndex(
            model_name='inward',
            name='inventory_i_variety_f81fc6_idx',
        ),
        migrations.RemoveIndex(
            model_name='inward',
            name='inventory_i_party_i_acfa50_idx',
        ),
        migrations.RemoveIndex(
            model_name='inward',
            name='inventory_i_date_23c69b_idx',
        ),
        migrations.RemoveIndex(
            model_name='outward',
            name='inventory_o_variety_3a2f4f_idx',
        ),
        migrations.RemoveIndex(
            model_name='outward',
            name='inventory_o_party_i_1f8f73_idx',
        ),
        migrations.RemoveIndex(
            model_name='outward',
            name='inventory_o_date_d414d4_idx',
        ),
        migrations.RemoveField(
            model_name='inward',
            name='total_kgs',
        ),
        migrations.RemoveField(
            model_name='outward',
            name='total_kgs',
        ),
        migrations.AddField(
            model_name='inward',
            name='avg_rate_per_q',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='inward',
            name='cutting',
            field=models.CharField(default='49 x 12', max_length=50),
        ),
        migrations.AddField(
            model_name='inward',
            name='from_location',
            field=models.CharField(default='MILL', max_length=150),
        ),
        migrations.AddField(
            model_name='inward',
            name='lorry_no',
            field=models.CharField(default='NONE', max_length=50),
        ),
        migrations.AddField(
            model_name='inward',
            name='moisture',
            field=models.DecimalField(decimal_places=2, default=Decimal('13.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='inward',
            name='net_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='inward',
            name='to_location',
            field=models.CharField(default='GODOWN 1', max_length=150),
        ),
        migrations.AddField(
            model_name='inward',
            name='type_of_movement',
            field=models.CharField(default='Purchase', max_length=100),
        ),
        migrations.AddField(
            model_name='inward',
            name='wb_no',
            field=models.CharField(default='12345', max_length=50),
        ),
        migrations.AddField(
            model_name='outward',
            name='cutting',
            field=models.CharField(default='49 x 12', max_length=50),
        ),
        migrations.AddField(
            model_name='outward',
            name='from_location',
            field=models.CharField(default='GODOWN 1', max_length=150),
        ),
        migrations.AddField(
            model_name='outward',
            name='lorry_no',
            field=models.CharField(default='NONE', max_length=50),
        ),
        migrations.AddField(
            model_name='outward',
            name='moisture',
            field=models.DecimalField(decimal_places=2, default=Decimal('13.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='outward',
            name='net_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='outward',
            name='to_location',
            field=models.CharField(default='MILL', max_length=150),
        ),
        migrations.AddField(
            model_name='outward',
            name='type_of_movement',
            field=models.CharField(default='Sale / Issue', max_length=100),
        ),
        migrations.AddField(
            model_name='outward',
            name='wb_no',
            field=models.CharField(default='12345', max_length=50),
        ),
        migrations.AlterField(
            model_name='inward',
            name='lf_toggle',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inward',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inwards', to='inventory.party', verbose_name='Broker / From Party'),
        ),
        migrations.AlterField(
            model_name='inward',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='outward',
            name='lf_toggle',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='outward',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outwards', to='inventory.party', verbose_name='Broker / Customer'),
        ),
        migrations.AlterField(
            model_name='outward',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
