# Generated by Django 5.2.16 on 2026-07-23 09:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_dailystocksummary_inventory_d_variety_b2ad19_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inward',
            name='avg_rate_per_q',
        ),
        migrations.RemoveField(
            model_name='inward',
            name='cutting',
        ),
        migrations.RemoveField(
            model_name='inward',
            name='from_location',
        ),
        migrations.RemoveField(
            model_name='inward',
            name='lorry_no',
        ),
        migrations.RemoveField(
            model_name='inward',
            name='moisture',
        ),
        migrations.RemoveField(
            model_name='inward',
            name='net_weight',
        ),
        migrations.RemoveField(
            model_name='inward',
            name='to_location',
        ),
        migrations.RemoveField(
            model_name='inward',
            name='type_of_movement',
        ),
        migrations.RemoveField(
            model_name='inward',
            name='wb_no',
        ),
        migrations.RemoveField(
            model_name='outward',
            name='cutting',
        ),
        migrations.RemoveField(
            model_name='outward',
            name='from_location',
        ),
        migrations.RemoveField(
            model_name='outward',
            name='lorry_no',
        ),
        migrations.RemoveField(
            model_name='outward',
            name='moisture',
        ),
        migrations.RemoveField(
            model_name='outward',
            name='net_weight',
        ),
        migrations.RemoveField(
            model_name='outward',
            name='to_location',
        ),
        migrations.RemoveField(
            model_name='outward',
            name='type_of_movement',
        ),
        migrations.RemoveField(
            model_name='outward',
            name='wb_no',
        ),
        migrations.AddField(
            model_name='inward',
            name='total_kgs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='outward',
            name='total_kgs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inward',
            name='lf_toggle',
            field=models.BooleanField(default=False, verbose_name='LF Toggle (Yes/No)'),
        ),
        migrations.AlterField(
            model_name='inward',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inwards', to='inventory.party'),
        ),
        migrations.AlterField(
            model_name='inward',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='outward',
            name='lf_toggle',
            field=models.BooleanField(default=False, verbose_name='LF Toggle (Yes/No)'),
        ),
        migrations.AlterField(
            model_name='outward',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outwards', to='inventory.party'),
        ),
        migrations.AlterField(
            model_name='outward',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='inward',
            index=models.Index(fields=['variety', '-date', '-id'], name='inventory_i_variety_f81fc6_idx'),
        ),
        migrations.AddIndex(
            model_name='inward',
            index=models.Index(fields=['party', '-date'], name='inventory_i_party_i_acfa50_idx'),
        ),
        migrations.AddIndex(
            model_name='inward',
            index=models.Index(fields=['-date'], name='inventory_i_date_23c69b_idx'),
        ),
        migrations.AddIndex(
            model_name='outward',
            index=models.Index(fields=['variety', '-date', '-id'], name='inventory_o_variety_3a2f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='outward',
            index=models.Index(fields=['party', '-date'], name='inventory_o_party_i_1f8f73_idx'),
        ),
        migrations.AddIndex(
            model_name='outward',
            index=models.Index(fields=['-date'], name='inventory_o_date_d414d4_idx'),
        ),
    ]
