# Generated by Django 5.2.16 on 2026-07-23 13:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inward_avg_rate_per_q_remove_inward_cutting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inward',
            name='lf_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Custom LF rate per bag if LF toggle is enabled', max_digits=8),
        ),
        migrations.AddField(
            model_name='outward',
            name='lf_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Custom LF rate per bag if LF toggle is enabled', max_digits=8),
        ),
    ]
