# Generated by Django 5.2.16 on 2026-07-23 16:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inward_lf_rate_outward_lf_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inward',
            name='lf_rate',
        ),
        migrations.RemoveField(
            model_name='outward',
            name='lf_rate',
        ),
        migrations.AddField(
            model_name='inward',
            name='lf_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total LF charge amount entered directly by the user', max_digits=12),
        ),
        migrations.AddField(
            model_name='inward',
            name='per_bag_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Auto-calculated actual cost per bag', max_digits=12),
        ),
        migrations.AddField(
            model_name='outward',
            name='lf_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total LF charge amount entered directly by the user', max_digits=12),
        ),
        migrations.AddField(
            model_name='outward',
            name='per_bag_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Auto-calculated actual cost per bag', max_digits=12),
        ),
    ]
