# Generated by Django 5.2.16 on 2026-08-22 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_approvalrequest_requested_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inward',
            index=models.Index(fields=['date', 'variety'], name='inventory_i_date_38988d_idx'),
        ),
        migrations.AddIndex(
            model_name='inward',
            index=models.Index(fields=['created_by'], name='inventory_i_created_438328_idx'),
        ),
        migrations.AddIndex(
            model_name='outward',
            index=models.Index(fields=['date', 'variety'], name='inventory_o_date_46476f_idx'),
        ),
        migrations.AddIndex(
            model_name='outward',
            index=models.Index(fields=['created_by'], name='inventory_o_created_4cf79a_idx'),
        ),
    ]
