# Generated by Django 5.2.16 on 2026-08-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_transfer_fields_and_manual_invoice'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='outward',
            new_name='inventory_o_to_plac_9d089e_idx',
            old_name='inventory_o_to_plac_e65d83_idx',
        ),
        migrations.AlterField(
            model_name='inward',
            name='invoice_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='outward',
            name='invoice_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
