# Generated by Django 5.2.16 on 2026-09-03 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_rename_inventory_o_to_plac_e65d83_idx_inventory_o_to_plac_9d089e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outward',
            name='from_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_outwards', to='inventory.place'),
        ),
    ]
