# Generated by Django 5.2.16 on 2026-09-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_outward_from_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='variety',
            name='photo_data',
            field=models.TextField(blank=True, help_text='Base64 image data for permanent cloud database storage', null=True),
        ),
    ]
