# Generated by Django 5.2.16 on 2026-09-17 10:23

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_variety_photo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variety',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=inventory.models.variety_photo_upload_path),
        ),
    ]
